13.0 website login redirect back
itpp-labs/website-addons pull request #619
Opened 2021-04-21 10:30 UTC by mentalko

Доработка документации https://github.com/itpp-labs/website-addons/pull/559

2021-05-04 16:14 UTC, trojikman commented
Динар ругается на форматирование, снова надо применить пре коммит, коммиты с прекоммитом потом надо будет объединить в один. Для такого типа коммитов можно использовать :rainbow:

2021-05-04 16:15 UTC, trojikman requested changes
Динар ругается на форматирование, снова надо применить пре коммит, коммиты с прекоммитом потом надо будет объединить в один. Для такого типа коммитов можно использовать rainbow

2021-05-05 08:06 UTC, yelizariev requested changes

2021-05-05 08:06 UTC, yelizariev commented on website_login_redirect_back/doc/index.rst
> +    * Or create a new user in the user settings with ``User Type: Portal``
```suggestion
Make sure that you have a user with **User Type**->*Portal*. if you have demo data installed, there is a portal user with following credentials:

       * Email: ``portal``
       * Password: ``portal``

Or just create a new user with **User Type** -> *Portal*
```

2021-05-05 08:06 UTC, yelizariev commented on website_login_redirect_back/doc/index.rst
> +* Log out from the site
```suggestion
* Log out from the website
```

2021-05-05 08:06 UTC, yelizariev commented on website_login_redirect_back/doc/index.rst
> +* Go to any page of your site (only not to the main page)
```suggestion
* Go to any page of your website
```

2021-05-05 08:06 UTC, yelizariev commented on website_login_redirect_back/doc/index.rst
> +* Click the ``[Sing in]`` button in the caption of the page.
```suggestion
* Click the ``[Sing in]`` button
```

2021-05-05 08:06 UTC, yelizariev commented on website_login_redirect_back/doc/index.rst
> +* After a successful login, you will be redirected to the page you were on before login
```suggestion
* RESULT: after successful login, you will be redirected to the page you were on before authentication
```

2021-05-06 18:46 UTC, mentalko commented on website_login_redirect_back/controllers/main.py
> +                redirect = b'/web?' + request.httprequest.query_string
Вставил в адресную строку -> залогинился -> открылась скопированная страница.

2021-05-07 07:10 UTC, yelizariev commented on chess/models/models.py
> +            self._cr.dbname,
Ты сломал ПР

2021-05-07 07:13 UTC, yelizariev commented on chess/models/models.py
> +            self._cr.dbname,
что-то вроде этого

```
cd website_login_redirect_back
pre-commit run --files=$(find . -type f)
```

2021-05-10 15:17 UTC, yelizariev commented on website_login_redirect_back/README.rst
> +Say you are on the `/blog` page and click `Sing in` in the caption of the page to logging in.
```suggestion
For example, you are on the `/blog` page and click `Sign in` button to log in.
```

2021-05-10 15:17 UTC, yelizariev commented on website_login_redirect_back/__manifest__.py
> +    "name": "Website Login Redirect Back",
Аналогично в других местах
```suggestion
    "name": "Login Page Redirection",
```

2021-05-10 15:17 UTC, yelizariev commented on website_login_redirect_back/__manifest__.py
> +    "summary": "Redirects the user at the same page from where he logs in",
```suggestion
    "summary": "Redirects portal user to the page which was right before authentication",
```

2021-05-10 15:17 UTC, yelizariev commented on website_login_redirect_back/doc/index.rst
> +===========================
Вторая строка должна закачиваться и начинаться с пробела, а знаки = должно быть столько сколько знаков на второй строке включая пробелы

2021-05-17 10:05 UTC, trojikman approved these changes

2021-05-17 10:06 UTC, trojikman commented
I approve to merge it now

2021-05-17 10:06 UTC, merged